// AUTH
export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE";
export const LOGOUT = "LOGOUT";


// ITEMS
export const GET_SINGLE_ITEM = "GET_SINGLE_ITEM";
export const SET_SINGLE_ITEM = "SET_SINGLE_ITEM";
export const UPDATE_SINGLE_ITEM = "UPDATE_SINGLE_ITEM";
export const LOADING_SINGLE_ITEM = "LOADING_SINGLE_ITEM";
export const SET_ALL_ITEMS = "SET_ALL_ITEMS";
export const LOADING_ALL_ITEMS = "LOADING_ALL_ITEMS";
export const RELOAD_ITEMS = "RELOAD_ITEMS";


// USERS
export const UPDATING_USER_INFO = "UPDATING_USER_INFO";
export const FETCH_USER_INFO = "FETCH_USER_INFO";
