// AUTH
export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE";
export const LOGOUT = "LOGOUT";


// POSTS
export const SET_ITEM = "SET_ITEM";
export const SET_ITEMS = "SET_ITEMS";
export const LOADING_ITEM = "LOADING_ITEM";
export const LOADING_ITEMS = "LOADING_ITEMS";


// USERS
export const UPDATING_USER_INFO = "UPDATING_USER_INFO";
export const FETCH_USER_INFO = "FETCH_USER_INFO";